# Generated by Django 4.2 on 2026-07-16 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_alter_product_color_alter_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(choices=[('best', 'Best Seller'), ('new', 'New Arrival'), ('hot', 'Hot Sale')], default='best', max_length=10),
        ),
    ]
