# Generated by Django 4.2 on 2026-07-25 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0005_payment_details_customer_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('contact', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('address1', models.TextField()),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('pincode', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.order')),
                ('payment_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.payment_details')),
            ],
            options={
                'db_table': 'billing_details',
            },
        ),
        migrations.DeleteModel(
            name='Customer_details',
        ),
    ]
